server:
  port: 8081

spring:
  application:
    name: inventory
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
