spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/inventory
    username: postgres
    password: '{cipher}293996a59cb92ec86a5191de2202dbd19865b45d382e9e9ff957de5f0059f723'

  jpa:
    hibernate:
      ddl-auto: update

# APP-SPECIFIC CONFIG
inventory:
  active: ${spring.profiles.active}